config_creator/config_creator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve as staticserveview
from rest_framework import routers

router = routers.DefaultRouter()


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("core.urls")),
    path("api/", include("database_interface_api.urls")),
    path("", include("django.contrib.auth.urls")),
    path("api/", include("core_api.urls")),
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(
        r"^media/(?P<path>.*)$", staticserveview, {"document_root": settings.MEDIA_ROOT}
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config_creator/core/urls.py
from .views import *
from django.contrib.auth.decorators import login_required
from django.urls import include, path

urlpatterns = [
    path("", login_required(index), name="home"),
    path("job/", include("core.job_urls")),
    path("", include("core.file_upload_urls")),
    path("job/<int:job_id>/", include("core.jobtask_urls")),
    path("job/<int:job_id>/task/<int:task_id>/", include("core.jobtask_field_urls")),
    path("job/<int:job_id>/task/<int:task_id>/", include("core.jobtask_join_urls")),
    path("job/<int:job_id>/task/<int:task_id>/", include("core.jobtask_where_urls")),
    path("job/<int:job_id>/task/<int:task_id>/", include("core.jobtask_delta_urls")),
    path(
        "job/<int:job_id>/task/<int:task_id>/", include("core.jobtask_dependency_urls")
    ),
]

config_creator/core/models.py
import re
import sys

from django.db import models
from django.conf import settings
from django.db.models import Q
from django.urls import reverse
from lib.helper import ifnull
from wordsegment import segment

__all__ = [
    "JobType",
    "TaskType",
    "TableType",
    "WriteDisposition",
    "LogicOperator",
    "Operator",
    "JoinType",
    "JobToTaskType",
    "Job",
    "JobTask",
    "History",
    "Field",
    "Dependency",
    "DrivingColumn",
    "Partition",
    "HistoryOrder",
    "Delta",
    "Join",
    "Condition",
    "BatchJobProperties",
    "DEFAULT_TASK_ID",
    "DEFAULT_TABLE_ID",
    "DEFAULT_WRITE_DISPOSITION_ID",
    "DEFAULT_LOGIC_OPERATOR_ID",
    "DEFAULT_OPERATOR_ID",
    "DEFAULT_JOIN_ID",
    "DagJobProperties",
    "BatchCustomJobTaskProperties",
    "BigQueryDataType",
    "DATA_TYPE_MAPPING",
    "changefieldposition",
    "DEFAULT_DATA_TYPE_ID",
    "SourceTable",
    "changeorderposition",
    "get_source_table",
    "Function",
    "FunctionType",
    "FunctionToTaskType",
    "TaskTypeToWriteDisposition",
    "sk_transformation",
]

User = settings.AUTH_USER_MODEL

DATA_TYPE_MAPPING = {
    "CHAR": "STRING",
    "VARCHAR": "STRING",
    "VARCHAR2": "STRING",
    "DATE": "DATE",
    "TIMESTAMP": "TIMESTAMP",
    "BYTEINT": "INT64",
    "SMALLINT": "INT64",
    "INTEGER": "INT64",
    "BIGINT": "INT64",
    "NUMBER": "NUMERIC",
    "NUMERIC": "NUMERIC",
    "DECIMAL": "NUMERIC",
    "BINARY DOUBLE": "FLOAT64",
    "DOUBLE PRECISION": "FLOAT64",
    "BINARY FLOAT": "FLOAT64",
    "DOUBLE": "FLOAT64",
    "BOOL": "BOOL",
    "STRING": "STRING",
    "FLOAT64": "FLOAT64",
    "INT64": "INT64",
}

DEFAULT_ID = 1
DEFAULT_TASK_ID = DEFAULT_ID
DEFAULT_TABLE_ID = DEFAULT_ID
DEFAULT_WRITE_DISPOSITION_ID = DEFAULT_ID
DEFAULT_LOGIC_OPERATOR_ID = DEFAULT_ID
DEFAULT_OPERATOR_ID = DEFAULT_ID
DEFAULT_JOIN_ID = DEFAULT_ID
DEFAULT_DATA_TYPE_ID = DEFAULT_ID


class JobType(models.Model):
    name = models.CharField(
        verbose_name="Job Type",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name


class TaskType(models.Model):
    name = models.CharField(
        verbose_name="Task Type",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name


class TableType(models.Model):
    name = models.CharField(
        verbose_name="Table Type",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name


class WriteDisposition(models.Model):
    name = models.CharField(
        verbose_name="Write Disposition",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name

    def todict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "code": self.code,
            "description": ifnull(self.description, ""),
        }


class TaskTypeToWriteDisposition(models.Model):
    write_disposition = models.ForeignKey(
        WriteDisposition, null=False, on_delete=models.CASCADE
    )
    task_type = models.ForeignKey(TaskType, null=False, on_delete=models.CASCADE)

    def __str__(self) -> str:
        """
        The function returns a string that is the name of the task type and the name of the write
        disposition

        Returns:
          The name of the task type and the name of the write disposition.
        """
        return f"{self.task_type.name}: {self.write_disposition.name}"


class LogicOperator(models.Model):
    name = models.CharField(
        verbose_name="Logic Operator",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name

    def lower(self) -> str:
        """
        This function takes in a string and returns a lowercase version of that string

        Returns:
          The name of the object in lowercase.
        """
        return str(self.name).lower()


class Operator(models.Model):
    name = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    symbol = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(
        blank=True,
        null=True,
    )

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name

    def lower(self) -> str:
        """
        This function takes in a string and returns a lowercase version of that string

        Returns:
          The name of the object in lowercase.
        """
        return str(self.name).lower()


class JoinType(models.Model):
    name = models.CharField(
        verbose_name="Join Type",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name


class BigQueryDataType(models.Model):
    name = models.CharField(
        verbose_name="Data Type",
        max_length=255,
        blank=False,
        null=False,
        help_text="",
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name


class FunctionType(models.Model):
    name = models.CharField(
        verbose_name="Function Type",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )

    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name

    def todict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
        }


class Function(models.Model):
    name = models.CharField(
        verbose_name="Name",
        max_length=255,
        blank=False,
        null=False,
    )
    syntax = models.CharField(
        max_length=255,
        blank=False,
        null=False,
    )

    description = models.TextField(blank=True, null=True)
    type = models.ForeignKey(FunctionType, null=False, on_delete=models.CASCADE)
    return_type = models.ForeignKey(
        BigQueryDataType, null=False, on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        """
        The function returns a string that is the name of the type of the pokemon and the name of the
        pokemon

        Returns:
          The name of the type of the pokemon and the name of the pokemon.
        """
        return f"{self.type.name} - {self.name}"

    def todict(self):
        return {
            "id": self.id,
            "name": self.name,
            "syntax": self.syntax,
            "description": self.description,
            "type": self.type.name,
            "return_type": self.return_type.name,
        }


class FunctionToTaskType(models.Model):
    function = models.ForeignKey(Function, null=False, on_delete=models.CASCADE)
    tasktype = models.ForeignKey(TaskType, null=False, on_delete=models.CASCADE)

    def __str__(self) -> str:
        """
        The function returns a string that is the name of the function and the name of the tasktype

        Returns:
          The name of the function and the name of the tasktype.
        """

config_creator/core/forms.py
import sys

from .models import (
    BigQueryDataType,
    Job,
    JobTask,
    Field,
    Join,
    Condition,
    Delta,
    Dependency,
    BatchJobProperties,
    DagJobProperties,
    BatchCustomJobTaskProperties,
)
from django import forms
from django.core.exceptions import ValidationError

__all__ = [
    "UploadFileForm",
    "JobTaskForm",
    "FieldForm",
    "JoinForm",
    "ConditionForm",
    "DeltaForm",
    "DependencyForm",
    "JobForm",
    "BatchJobPropertiesForm",
    "DagJobPropertiesForm",
]


def validate_file_extension(value):
    if not value.name.endswith(".json"):
        raise ValidationError("Only JSON files can be loaded.", code="invalid")


class UploadFileForm(forms.Form):
    title = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={"hidden": True}),
    )
    file = forms.FileField(
        widget=forms.FileInput(attrs={"class": "box__file"}),
        validators=[validate_file_extension],
    )


class JobTaskForm(forms.ModelForm):
    class Meta:
        model = JobTask
        fields = [
            "name",
            "type",
            "description",
            "properties",
            "write_disposition",
            "destination_table",
            "destination_dataset",
            "driving_table",
            "staging_dataset",
            "table_type",
            "job",
        ]


class FieldForm(forms.ModelForm):

    data_type = forms.ModelChoiceField(
        queryset=BigQueryDataType.objects.order_by("name")
    )

    class Meta:
        model = Field
        fields = [
            "name",
            "source_column",
            "source_table",
            "transformation",
            "is_primary_key",
            "is_nullable",
            "position",
            "data_type",
            "source_data_type",
            "default",
        ]


class JoinForm(forms.ModelForm):
    class Meta:
        model = Join
        fields = [
            "type",
            "left_table",
            "right_table",
        ]


class ConditionForm(forms.ModelForm):
    class Meta:
        model = Condition
        fields = [
            "operator",
            "logic_operator",
            "left",
            "right",
        ]


class DeltaForm(forms.ModelForm):
    class Meta:
        model = Delta
        fields = [
            "field",
            "lower_bound",
            "upper_bound",
        ]


class DependencyForm(forms.ModelForm):
    class Meta:
        model = Dependency
        fields = [
            "predecessor",
            "dependant",
        ]


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = [
            "name",
            "type",
            "description",
            "id",
        ]


class BatchJobPropertiesForm(forms.ModelForm):
    class Meta:
        model = BatchJobProperties
        fields = [
            "prefix",
            "dataset_source",
            "dataset_staging",
            "dataset_publish",
            "source_project",
            "target_project",
        ]


class DagJobPropertiesForm(forms.ModelForm):
    class Meta:
        model = DagJobProperties
        fields = [
            "dataset_source",
            "dataset_staging",
            "dataset_publish",
            "source_project",
            "target_project",
            "owner",
            "email",
            "tags",
            "imports",
        ]


class BatchCustomJobTaskPropertiesForm(forms.ModelForm):
    class Meta:
        model = BatchCustomJobTaskProperties
        fields = [
            "sql",
        ]


def str_to_form(formname):
    """
    It takes a string and returns a form

    Args:
      formname: The name of the form to be loaded.

    Returns:
      The form object.
    """
    try:
        return getattr(sys.modules[__name__], formname)
    except AttributeError:
        return None

config_creator/core/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" /> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="/static/css/main.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="/static/css/prism.css" rel="stylesheet" />

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <title>{% block title %}{% endblock %} | Config Creator</title>
    <!-- <link rel="icon" href="" type="image/x-icon"> -->
  </head>
  <body>
    <div class="bg-dark position-relative bd-example-toasts" aria-live="polite" aria-atomic="true">
      <div class="toast-container position-absolute top-0 end-0 p-3 p-3 z-1" id="toastPlacement">
        {% if messages %}
          {% for message in messages %}
              <div class="toast alert-{{ message.tags }}">
                <div class="toast-header">
                  <strong class="me-auto">{{ message.tags }}</strong>
                  <button class="btn-close" type="button" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                  {{ message }}
                </div>
              </div>
          {% endfor %}
        {% endif %}    
        
        {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
              <div class="toast alert-warning">
                <div class="toast-header">
                  <strong class="me-auto">{{ field.label_tag }}</strong>
                  <button class="btn-close" type="button" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                  {{ error }}
                </div>
              </div>
          {% endfor %}
        {% endfor %}
      {% endif %}
      </div>
    </div>
    <main>
      <div class="nav-col">
        {% block nav %}
          {% include "nav.html" %}
        {% endblock %}
      </div>
      <div class="content-col">
        <div class="row">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </main>
    
    <script>
      const toastList = document.getElementsByClassName("toast");
      for (var i = 0; i < toastList.length; i++) {
        const toast = new bootstrap.Toast(toastList[i]);
        toast.show();
      }
    </script>
    <script>
      var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
      var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
        return new bootstrap.Popover(popoverTriggerEl)
      })
    </script>
    <script src="/static/js/main.js" ></script>
    <script src="/static/js/connection-selector.js" ></script>
</body>
</html>

config_creator/core/templates/fileselect.html
{% extends 'base.html' %}
{% block title %}File Upload{% endblock %}
{% block content %}
{% load static %}
<link href="{% static 'css\file-upload.css' %}" rel="stylesheet"/>
<div class="upload-container container" role="main">
  <div class="py-1 text-center">
    <h2>Upload from local directory</h2>
    <p class="lead">Load a config file you have stored on your local machine.</p>
  </div>

  <form class="box rounded has-advanced-upload" id="id_drop_zone_form" method="post" action="{% url 'file-upload' %}" enctype="multipart/form-data">  
    {% csrf_token %}
    <div class="drop-zone" id="id_drop_zone">
      <div class="box__input js">
        <svg class="box__icon" xmlns="http://www.w3.org/2000/svg" width="50" height="43" viewBox="0 0 50 43"><path d="M48.4 26.5c-.9 0-1.7.7-1.7 1.7v11.6h-43.3v-11.6c0-.9-.7-1.7-1.7-1.7s-1.7.7-1.7 1.7v13.2c0 .9.7 1.7 1.7 1.7h46.7c.9 0 1.7-.7 1.7-1.7v-13.2c0-1-.7-1.7-1.7-1.7zm-24.5 6.1c.3.3.8.5 1.2.5.4 0 .9-.2 1.2-.5l10-11.6c.7-.7.7-1.7 0-2.4s-1.7-.7-2.4 0l-7.1 8.3v-25.3c0-.9-.7-1.7-1.7-1.7s-1.7.7-1.7 1.7v25.3l-7.1-8.3c-.7-.7-1.7-.7-2.4 0s-.7 1.7 0 2.4l10 11.6z"/></svg>
        <label id="id_file-label" for="id_file"><strong>Choose a file</strong><span class="box__dragndrop"> or drag it here</span>.</label>
        <input id="id_title" name="title" type="text" hidden/>
        <input id="id_file" name="file" type="file" hidden/>
      </div>
    </div>
  </form>
</div>
<script src="/static/js/lazy-listener.js"></script>
<script src="{% static 'js\form-upload.js' %}"></script>
{% endblock %}

config_creator/core/templates/fileselect_git.html
{% extends "base.html" %}

{% block title %}Git Repositories{% endblock %}
        {% block content %}
        {% autoescape off %}
        <div class="container">
          <div class="py-1 text-center">
            <h2>{{repo.name}}</h2>
          </div>
          <div class="row g-5">
            <div class="col-md-6 col-lg-6">
              <div class="row g-3">
                <div class="container py3">
                  <p class="lead">Select a config file to load.</p>
                  <ul>
                  {% for file in files %}
                    {{file}}
                  {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-md-6 col-lg-6">
              <form action="." method="post">
                <input id="id_path" name="path" type="text" hidden />
                <div id="id_message_wrapper">
                  <label id="id_message"></label>
                </div>
                <div class="container py-3">
                  <a class="btn btn-secondary" id="id_cancel" href="{% url 'repository-list' %}" title=""><i class="bi bi-x-lg"></i> Cancel</a>
                  <button class="btn btn-primary" id="id_load" type="submit" hidden><i class="bi bi-upload"></i> Load</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        {% endautoescape %}
        <script>
          var elements = document.getElementsByClassName("tree-file");

          var setActive = function() {
            for (var i = 0; i < elements.length; i++) {
                elements[i].classList.remove("tree-file-active");
            }
            this.classList.add("tree-file-active");
            document.getElementById("id_path").value = this.dataset.path;
            document.getElementById("id_message").innerHTML = "Would you like to load file: " + this.dataset.path;
            document.getElementById("id_load").removeAttribute("hidden");
          };

          for (var i = 0; i < elements.length; i++) {
              elements[i].addEventListener('click', setActive, false);
          }
        </script>
        {% endblock %}

config_creator/core/templates/footer.html
<footer class="row g-3 py-5">
  <div class="container align-middle">
  </div>
</footer>

config_creator/core/templates/git_file_selector.html
<div class="modal" id="id_git_file_select_modal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered selector-dialog">
    <div class="modal-content selector-content">
      <div class="modal-header selector-header">
        <div class="col-5"><h5 class="modal-title">Select from repository</h5></div>
        <div class="col-5">
          <div class="row visually-hidden" id="id_branch_wrapper">
            <div class="col-8"> 
              <select id="id_branch">
              </select> 
            </div>
            <div class="col-4">
              <button class="btn btn-primary" id="id_submit_branch" type="button" style="padding: 1px 6px;"><i class="bi bi-arrow-repeat"></i> Switch Branch</button>
            </div>
          </div>
        </div>
        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="container modal-content-spinner-container" id="id_git_file_select_modal_content">

      </div>
      <div class="modal-footer" id="id_selection_wrapper">
        <div class="lead" id="id_selection"></div>
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<script>
$(document).ready(function() {
  $('#id_branch').select2({
        dropdownParent: $('#id_git_file_select_modal'),
        width: "100%"
    });
});
</script>
<script>
const gitMap = new Map([
    ['id_submit_branch', {
      'function': 'submitBranch(this.dataset["repoId"])',
      'type': 'click'
    }]
  ]).forEach(addListener)

</script>

config_creator/core/templates/repositories.html
{% extends "base.html" %}

{% block title %}Git Repositories{% endblock %}
        {% block content %}
        <div class="container">
          <div class="py-1 text-center">
            <h2>Git Repositories</h2>
            <p class="lead">Load config file from git.</p>
          </div>
          <div class="container">
            <table class="table table-hover align-middle">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for repo in repositories %}
                  <tr>
                    <td>{{ repo.name }}</td>
                    <td class="btn-column"><button class="btn row-btn-secondary repo-button" id="id_repo_button_{{repo.id}}" title="Pull from repository" aria-current="page" data-bs-toggle="tooltip" data-bs-placement="right" data-repo-id="{{repo.id}}"><i class="fa-solid fa-code-pull-request"></i></button></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#changeForm"><i class="fa-solid fa-code-pull-request"></i> Pull from new repository</button>
        </div>

        <div class="modal" id="changeForm" tabindex="-1">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Add new repository</h5>
                <button  class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <form action="{% url 'repository-pull-new' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body modal-dialog-centered">
                  <div class="row g-3">
                    <div class="col-12">
                      <div class="form-floating">
                        <input class="form-control" id="id_name" name="name" type="text" maxlength="250" />
                        <label for="id_name">Repository Name</label>
                      </div>
                    </div>
            
                    <div class="col-12">
                      <div class="form-floating">
                        <input class="form-control" id="id_url" name="url" type="text" maxlength="250" />
                        <label for="id_url">Repository URL</label>
                      </div>
                    </div>
            
                  </div>
                </div> 
                <div class="modal-footer">
                  <button class="btn btn-secondary" type="button" data-bs-dismiss="modal"><i class="bi bi-x-lg"></i> Cancel</button>
                  <button class="btn btn-primary" type="submit" ><i class="fa-solid fa-code-pull-request"></i> Pull</button>
                </div>
              </form>
            </div>
          </div>
        </div>

        <script src="/static/js/lazy-listener.js"></script>
        <script src="/static/js/git-file-selector.js"></script>
        {% include 'git_file_selector.html' %}

        <script>

          let listenerMap = new Map()

          let repoButtonList = document.getElementsByClassName('repo-button')
          for (let i = 0; i < repoButtonList.length; i++) {
            listenerMap.set(repoButtonList[i].id, {
                  'function': 'openGitModal(this.dataset["repoId"])',
                  'type': 'click'
                })
          }       
          
          listenerMap.forEach(addListener)
          
        </script>

        {% endblock %}

config_creator/core/templates/user_nav.html
    <div class="dropdown border-top">
      <a class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" href="#" title="" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-person-circle"></i>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
        <li><a class="dropdown-item" href="/admin" title="">Admin</a></li>
        <li><a class="dropdown-item" href="{% url 'profile' %}" title="">Profile</a></li>
        <li><hr class="dropdown-divider"/></li>
        <li><a class="dropdown-item" href="{% url 'logout' %}?next=/" title="">Sign out</a></li>
      </ul>
    </div>