config_creator/config_creator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve as staticserveview
from rest_framework import routers

router = routers.DefaultRouter()


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("core.urls")),
    path("api/", include("database_interface_api.urls")),
    path("", include("django.contrib.auth.urls")),
    path("api/", include("core_api.urls")),
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(
        r"^media/(?P<path>.*)$", staticserveview, {"document_root": settings.MEDIA_ROOT}
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config_creator/core/urls.py
from .views import *
from django.contrib.auth.decorators import login_required
from django.urls import include, path

urlpatterns = [
    path("", login_required(index), name="home"),
    path("job/", include("core.job_urls")),
    path("", include("core.file_upload_urls")),
    path("job/<int:job_id>/", include("core.jobtask_urls")),
    path("job/<int:job_id>/task/<int:task_id>/", include("core.jobtask_field_urls")),
    path("job/<int:job_id>/task/<int:task_id>/", include("core.jobtask_join_urls")),
    path("job/<int:job_id>/task/<int:task_id>/", include("core.jobtask_where_urls")),
    path("job/<int:job_id>/task/<int:task_id>/", include("core.jobtask_delta_urls")),
    path(
        "job/<int:job_id>/task/<int:task_id>/", include("core.jobtask_dependency_urls")
    ),
]

config_creator/core/models.py
import re
import sys

from django.db import models
from django.conf import settings
from django.db.models import Q
from django.urls import reverse
from lib.helper import ifnull
from wordsegment import segment

__all__ = [
    "JobType",
    "TaskType",
    "TableType",
    "WriteDisposition",
    "LogicOperator",
    "Operator",
    "JoinType",
    "JobToTaskType",
    "Job",
    "JobTask",
    "History",
    "Field",
    "Dependency",
    "DrivingColumn",
    "Partition",
    "HistoryOrder",
    "Delta",
    "Join",
    "Condition",
    "BatchJobProperties",
    "DEFAULT_TASK_ID",
    "DEFAULT_TABLE_ID",
    "DEFAULT_WRITE_DISPOSITION_ID",
    "DEFAULT_LOGIC_OPERATOR_ID",
    "DEFAULT_OPERATOR_ID",
    "DEFAULT_JOIN_ID",
    "DagJobProperties",
    "BatchCustomJobTaskProperties",
    "BigQueryDataType",
    "DATA_TYPE_MAPPING",
    "changefieldposition",
    "DEFAULT_DATA_TYPE_ID",
    "SourceTable",
    "changeorderposition",
    "get_source_table",
    "Function",
    "FunctionType",
    "FunctionToTaskType",
    "TaskTypeToWriteDisposition",
    "sk_transformation",
]

User = settings.AUTH_USER_MODEL

DATA_TYPE_MAPPING = {
    "CHAR": "STRING",
    "VARCHAR": "STRING",
    "VARCHAR2": "STRING",
    "DATE": "DATE",
    "TIMESTAMP": "TIMESTAMP",
    "BYTEINT": "INT64",
    "SMALLINT": "INT64",
    "INTEGER": "INT64",
    "BIGINT": "INT64",
    "NUMBER": "NUMERIC",
    "NUMERIC": "NUMERIC",
    "DECIMAL": "NUMERIC",
    "BINARY DOUBLE": "FLOAT64",
    "DOUBLE PRECISION": "FLOAT64",
    "BINARY FLOAT": "FLOAT64",
    "DOUBLE": "FLOAT64",
    "BOOL": "BOOL",
    "STRING": "STRING",
    "FLOAT64": "FLOAT64",
    "INT64": "INT64",
}

DEFAULT_ID = 1
DEFAULT_TASK_ID = DEFAULT_ID
DEFAULT_TABLE_ID = DEFAULT_ID
DEFAULT_WRITE_DISPOSITION_ID = DEFAULT_ID
DEFAULT_LOGIC_OPERATOR_ID = DEFAULT_ID
DEFAULT_OPERATOR_ID = DEFAULT_ID
DEFAULT_JOIN_ID = DEFAULT_ID
DEFAULT_DATA_TYPE_ID = DEFAULT_ID


class JobType(models.Model):
    name = models.CharField(
        verbose_name="Job Type",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name


class TaskType(models.Model):
    name = models.CharField(
        verbose_name="Task Type",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name


class TableType(models.Model):
    name = models.CharField(
        verbose_name="Table Type",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name


class WriteDisposition(models.Model):
    name = models.CharField(
        verbose_name="Write Disposition",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name

    def todict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "code": self.code,
            "description": ifnull(self.description, ""),
        }


class TaskTypeToWriteDisposition(models.Model):
    write_disposition = models.ForeignKey(
        WriteDisposition, null=False, on_delete=models.CASCADE
    )
    task_type = models.ForeignKey(TaskType, null=False, on_delete=models.CASCADE)

    def __str__(self) -> str:
        """
        The function returns a string that is the name of the task type and the name of the write
        disposition

        Returns:
          The name of the task type and the name of the write disposition.
        """
        return f"{self.task_type.name}: {self.write_disposition.name}"


class LogicOperator(models.Model):
    name = models.CharField(
        verbose_name="Logic Operator",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name

    def lower(self) -> str:
        """
        This function takes in a string and returns a lowercase version of that string

        Returns:
          The name of the object in lowercase.
        """
        return str(self.name).lower()


class Operator(models.Model):
    name = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    symbol = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(
        blank=True,
        null=True,
    )

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name

    def lower(self) -> str:
        """
        This function takes in a string and returns a lowercase version of that string

        Returns:
          The name of the object in lowercase.
        """
        return str(self.name).lower()


class JoinType(models.Model):
    name = models.CharField(
        verbose_name="Join Type",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    code = models.CharField(
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name


class BigQueryDataType(models.Model):
    name = models.CharField(
        verbose_name="Data Type",
        max_length=255,
        blank=False,
        null=False,
        help_text="",
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name


class FunctionType(models.Model):
    name = models.CharField(
        verbose_name="Function Type",
        max_length=255,
        blank=False,
        null=False,
        unique=True,
    )

    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        """
        The __str__() function returns a string representation of the object

        Returns:
          The name of the object.
        """
        return self.name

    def todict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
        }


class Function(models.Model):
    name = models.CharField(
        verbose_name="Name",
        max_length=255,
        blank=False,
        null=False,
    )
    syntax = models.CharField(
        max_length=255,
        blank=False,
        null=False,
    )

    description = models.TextField(blank=True, null=True)
    type = models.ForeignKey(FunctionType, null=False, on_delete=models.CASCADE)
    return_type = models.ForeignKey(
        BigQueryDataType, null=False, on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        """
        The function returns a string that is the name of the type of the pokemon and the name of the
        pokemon

        Returns:
          The name of the type of the pokemon and the name of the pokemon.
        """
        return f"{self.type.name} - {self.name}"

    def todict(self):
        return {
            "id": self.id,
            "name": self.name,
            "syntax": self.syntax,
            "description": self.description,
            "type": self.type.name,
            "return_type": self.return_type.name,
        }


class FunctionToTaskType(models.Model):
    function = models.ForeignKey(Function, null=False, on_delete=models.CASCADE)
    tasktype = models.ForeignKey(TaskType, null=False, on_delete=models.CASCADE)

    def __str__(self) -> str:
        """
        The function returns a string that is the name of the function and the name of the tasktype

        Returns:
          The name of the function and the name of the tasktype.
        """

config_creator/core/forms.py
import sys

from .models import (
    BigQueryDataType,
    Job,
    JobTask,
    Field,
    Join,
    Condition,
    Delta,
    Dependency,
    BatchJobProperties,
    DagJobProperties,
    BatchCustomJobTaskProperties,
)
from django import forms
from django.core.exceptions import ValidationError

__all__ = [
    "UploadFileForm",
    "JobTaskForm",
    "FieldForm",
    "JoinForm",
    "ConditionForm",
    "DeltaForm",
    "DependencyForm",
    "JobForm",
    "BatchJobPropertiesForm",
    "DagJobPropertiesForm",
]


def validate_file_extension(value):
    if not value.name.endswith(".json"):
        raise ValidationError("Only JSON files can be loaded.", code="invalid")


class UploadFileForm(forms.Form):
    title = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={"hidden": True}),
    )
    file = forms.FileField(
        widget=forms.FileInput(attrs={"class": "box__file"}),
        validators=[validate_file_extension],
    )


class JobTaskForm(forms.ModelForm):
    class Meta:
        model = JobTask
        fields = [
            "name",
            "type",
            "description",
            "properties",
            "write_disposition",
            "destination_table",
            "destination_dataset",
            "driving_table",
            "staging_dataset",
            "table_type",
            "job",
        ]


class FieldForm(forms.ModelForm):

    data_type = forms.ModelChoiceField(
        queryset=BigQueryDataType.objects.order_by("name")
    )

    class Meta:
        model = Field
        fields = [
            "name",
            "source_column",
            "source_table",
            "transformation",
            "is_primary_key",
            "is_nullable",
            "position",
            "data_type",
            "source_data_type",
            "default",
        ]


class JoinForm(forms.ModelForm):
    class Meta:
        model = Join
        fields = [
            "type",
            "left_table",
            "right_table",
        ]


class ConditionForm(forms.ModelForm):
    class Meta:
        model = Condition
        fields = [
            "operator",
            "logic_operator",
            "left",
            "right",
        ]


class DeltaForm(forms.ModelForm):
    class Meta:
        model = Delta
        fields = [
            "field",
            "lower_bound",
            "upper_bound",
        ]


class DependencyForm(forms.ModelForm):
    class Meta:
        model = Dependency
        fields = [
            "predecessor",
            "dependant",
        ]


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = [
            "name",
            "type",
            "description",
            "id",
        ]


class BatchJobPropertiesForm(forms.ModelForm):
    class Meta:
        model = BatchJobProperties
        fields = [
            "prefix",
            "dataset_source",
            "dataset_staging",
            "dataset_publish",
            "source_project",
            "target_project",
        ]


class DagJobPropertiesForm(forms.ModelForm):
    class Meta:
        model = DagJobProperties
        fields = [
            "dataset_source",
            "dataset_staging",
            "dataset_publish",
            "source_project",
            "target_project",
            "owner",
            "email",
            "tags",
            "imports",
        ]


class BatchCustomJobTaskPropertiesForm(forms.ModelForm):
    class Meta:
        model = BatchCustomJobTaskProperties
        fields = [
            "sql",
        ]


def str_to_form(formname):
    """
    It takes a string and returns a form

    Args:
      formname: The name of the form to be loaded.

    Returns:
      The form object.
    """
    try:
        return getattr(sys.modules[__name__], formname)
    except AttributeError:
        return None

config_creator/core/templates/core/condition_form.html
{% extends 'base.html' %}
{% block title %}Change Condition{% endblock %}
{% block content %}
{% load static %}
<div class="container">
  <div class="py-1 text-center">
    <h2>{% if join_id != None %}Join {% else %}Where {% endif %}Condition</h2>
    <p class="lead">Add or change your condition.</p>
  </div>
  <form id="id_form" method="post" 
    {% if condition_id != None %} 
      {% if join_id != None %} 
        action="{% url 'job-task-join-condition-update' job_id=job.id task_id=task.id join_id=join_id pk=condition_id %}" 
      {% else %}  
        action="{% url 'job-task-where-condition-update' job_id=job.id task_id=task.id pk=condition_id %}"
      {% endif %}
    {% else %}
      {% if join_id != None %} 
        action="{% url 'job-task-join-condition-add' job_id=job.id task_id=task.id join_id=join_id %}" 
      {% else %}
        action="{% url 'job-task-where-condition-add' job_id=job.id task_id=task.id %}"
      {% endif %}
    {% endif %}
    >
    {% csrf_token %}
    <div class="row g-5">
      <div class="col-md-12 col-lg-12">
        {% if condition_id != None %}
        <input id="id_id" name="id" value="{{ condition_id }}" hidden />
        {% else %}
        <input id="id_empty_id" name="id" hidden />
        {% endif %}
        <div class="row g-3">
          <div class="lead">Condition Details</div>
          <div class="col-sm-1">
            <div class="form-floating">
              {{form.logic_operator}}
            </div>
          </div>
          <div class="col-sm-4">
            <div class="input-group mb-3">
              <button class="input-group-text" id="id_value_1_tree" type="button" ><i class="fa-solid fa-folder-tree"></i></button>
              <div class="form-floating flex-grow-1">
                {% if condition_id != None %} 
                  <input class="form-control" id="id_left_field" name="left_field" type="text" value="{{ condition.left }}" maxlength="255" required="" aria-required="true" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" data-bs-animation="true" data-bs-content="Enter a column name (<dataset name>.<table name>.<column name>), value or sql function" />
                {% else %}
                  <input class="form-control" id="id_empty_left_field" name="left_field" type="text" maxlength="255" required="" aria-required="true" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" data-bs-animation="true" data-bs-content="Enter a column name (<dataset name>.<table name>.<column name>), value or sql function" />
                {% endif %} 
                <label for="id_left_field">Value 1:</label>
              </div>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-floating">
              {{form.operator}}
              {{form.operator.label_tag}}
            </div>
          </div>
          <div class="col-sm-4">
            <div class="input-group mb-3">
              <button class="input-group-text" id="id_value_2_tree" type="button" ><i class="fa-solid fa-folder-tree"></i></button>
              <div class="form-floating flex-grow-1">
                {% if condition_id != None %} 
                  <input class="form-control" id="id_right_field" name="right_field" type="text" value="{{ condition.right }}" maxlength="255" required="" aria-required="true" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" data-bs-animation="true" data-bs-content="Enter a column name (<dataset name>.<table name>.<column name>), value or sql function" />
                {% else %}
                  <input class="form-control" id="id_empty_right_field" name="right_field" type="text" maxlength="255" required="" aria-required="true" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" data-bs-animation="true" data-bs-content="Enter a column name (<dataset name>.<table name>.<column name>), value or sql function" />
                {% endif %} 
                <label for="id_right_field">Value 2:</label>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>  
    
    <div class="row g-5">
      <div class="col-md-4 col-lg-3 py-5">
          <button class="btn w-100 btn-primary" type="submit"><i class="bi bi-check-lg"></i> Save</button>
      </div>
      <div class="col-md-4 col-lg-3 py-5">
          <a class="w-100 btn btn-secondary" href="{% url 'job-task' job_id=job.id pk=task.id %}" title=""><i class="bi bi-x-lg"></i> Cancel</a>
      </div>
    </div>
  </form>
  <script src="/static/js/lazy-listener.js"></script>
  <script>
    
    let conditionListenerMap = new Map()
    
    {% if form.left.value != None %}
      conditionListenerMap.set("id_value_1_tree", {
            "function": "setReturnType('column', 'id_left_field', 'columnFull', null, null, null, null, null, false)",
            "type": "click"
          })
    {% else %}
      conditionListenerMap.set("id_value_1_tree", {
            "function": "setReturnType('column', 'id_empty_left_field', 'columnFull', null, null, null, null, null, false)",
            "type": "click"
          })
    {% endif %}

    {% if form.right.value != None %}
      conditionListenerMap.set("id_value_2_tree", {
            "function": "setReturnType('column', 'id_right_field', 'columnFull', null, null, null, null, null, false)",
            "type": "clikc"
          })
    {% else %}
      conditionListenerMap.set("id_value_2_tree", {
            "function": "setReturnType('column', 'id_empty_right_field', 'columnFull', null, null, null, null, null, false)",
            "type": "click"
          })
    {% endif %}
      
      conditionListenerMap.forEach(addListener)
  </script>
  {% include 'core/connection_selector.html' %}
</div>
{% endblock %}

config_creator/core/templates/core/connection_selector.html
<div class="modal" id="connection-modal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered selector-dialog">
    <div class="modal-content selector-content">
      <div class="modal-header selector-header">
        <h5 class="modal-title">Select from connection</h5>
        <!-- <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button> -->
      </div>
      <div class="container row g-3 py-3" id="id-modal-content">

      </div>
      <div class="modal-footer">
        <div class="lead" id="id_selection"></div>
        <button class="btn btn-secondary" id="id_connection_modal_close_button" type="button">Close</button>
        <button class="btn btn-success visually-hidden" id="id_submit_button" type="button" >Save changes</button>
      </div>
    </div>
  </div>
</div>

config_creator/core/templates/core/job_property_form.html
{% extends 'base.html' %}
{% block title %}Change Property{% endblock %}
{% block content %}
{% load static %}
<div class="container">
  <div class="py-1 text-center">
    <h2>Job Properties</h2>
    <p class="lead">View or change your job properties.</p>
  </div>
  <form method="post" 
  {% if pk != None %}
    action="{% url 'job-property-update' job_id=job_id pk=pk %}"
  {% else %}
   action="{% url 'job-property-add' job_id=job_id %}"
  {% endif %}
  >
  {% if pk != None %}
    <input id="id_id" name="id" value="{{ pk }}" hidden />
  {% else %}
    <input id="id_empty_id" name="id" hidden />
  {% endif %}
    {% csrf_token %}
    <div class="row g-5">
      <div class="col-md-12 col-lg-12">
        <div class="row g-3">
          {% for field in form %}
            <div class="col-6">
              <div class="form-floating">
                {{ field }}
                {{ field.label_tag }}
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>  
    <div class="row g-3 py-3 justify-content-end">
      <div class="col-md-2 col-lg-2">
        {% if job_id != None %}
          <a class="w-100 btn btn-secondary" href="{% url 'job-tasks' job_id=job_id %}" title=""><i class="bi bi-x-lg"></i> Cancel</a>
        {% else %}
          <a class="w-100 btn btn-secondary" href="{% url 'jobs' %}" title=""><i class="bi bi-x-lg"></i> Cancel</a>
        {% endif %}
      </div>
      <div class="col-md-2 col-lg-2">
        <button class="w-100 btn btn-primary" type="submit"><i class="bi bi-check-lg"></i> Save</button>
      </div>
    </div>
    
  </form>
</div>
{% endblock %}

config_creator/core/templates/core/job_tasks.html
{% extends 'base.html' %}
{% block title %}Job Tasks{% endblock %}
{% block content %}
{% load static %}
<div class="container">
  <div class="py-1 text-center">
    <h2>Job</h2>
    <p class="lead">View or change your job and it's tasks.</p>
  </div>
  <div class="row">
    <div class="col-md-11 col-lg-11">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'home' %}" title="Home">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'jobs' %}" title="Jobs">Jobs</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{job.name}}</li>
        </ol>
      </nav>
    </div>
    <div class="col-md-1 col-lg-1">
      <div class="dropdown">
        <a class="d-flex align-items-center justify-content-center link-dark text-decoration-none" id="dropdownJobTask" href="#" title="" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-three-dots"></i>
        </a>
        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
          <li><a class="dropdown-item" href="{% url 'job-update' pk=job.id %}" title="Edit">Edit Job Details</a></li>
          {% if property_id != None %}
            <li><a class="dropdown-item" href="{% url 'job-property-update' job_id=job.id pk=property_id %}" title="Edit">Edit Job Properties</a></li>
          {% else %}
            <li><a class="dropdown-item" href="{% url 'job-property-add' job_id=job.id %}" title="Edit">Edit Job Properties</a></li>
          {% endif %}
          <li><hr class="dropdown-divider"/></li>
          <li><a class="dropdown-item" id="id_download_config" href="{% url 'job-download' pk=job.id %}" title="Download">Download Config</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row g-5">
    <div class="col-md-12 col-lg-12">
      <p class="lead">Job Details</p>
      <div class="row g-3">
        <div class="col-6">
          <div class="form-floating">
            <input class="form-control" id="id_name" name="name" type="text" value="{{job.name}}" disabled />
            <label for="id_name">Job Name:</label>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="form-floating">
            <input class="form-control" id="id_type" name="type" type="text" value="{{job.type}}" disabled />
            <label for="id_type">Type:</label>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="form-floating">
            <input class="form-control" id="id_description" name="description" type="text" value="{{job.description}}" disabled />
            <label for="id_description">Description:</label>
          </div>
        </div>
      </div>
    </div>
  </div>
  

  <div class="row g-5 py-3">
    <div class="col-md-12 col-lg-12">
      <p class="lead">Properties</p>
      <div class="row g-3">
        {% for property in properties %}
          {% for key, value in property.items %}
            <div class="col-6">
              <div class="form-floating">
                <input id="id_{{ key }}" name="{{ key }}" type="text" value="{{ value }}" disabled />
                <label for="id_{{ key }}">{{ key }}:</label>
              </div>
            </div>
          {% endfor %}
        {% endfor %}
      </div>
    </div>
  </div>

  <div class="row g-5 py-3">
    <div class="lead">Tasks</div>
    <div class="row g-3">
      <table class="table table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Type</th>
            <th scope="col">Description</th>
            <th scope="col">Last Update</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for task in tasks %}
            <tr id="id_task_{{task.id}}_row">
              <td>{{ task.name }}</td>
              <td>{{ task.type }}</td>
              <td>{{ task.description }}</td>
              <td>{{ task.lastupdate }}</td>
              <td class="btn-column"><a class="btn row-btn-secondary" href="{% url 'job-task' job_id=job.id pk=task.id %}" title="View" aria-current="page" data-bs-toggle="tooltip" data-bs-placement="right"><i class="bi bi-search"></i></a></td>
              <td class="btn-column"><button class="btn row-btn-danger task-delete" id="id_task_delete_{{ task.id }}"
                type="button" title="Delete" aria-current="page" data-bs-toggle="tooltip" data-bs-placement="right"
                data-delete-url="{% url 'api-task-delete' job_id=job.id pk=task.id %}"
                data-delete-element-id="id_task_{{task.id}}_row"><i class="bi bi-trash3"></i></button></td>
            </tr>
          {% endfor %}
          {% if tasks|length == 0 %}
            <tr>
              <td class="text-center placeholder-row" colspan="6">No tasks linked to job!</td>
            </tr>
          {% endif %}
        </tbody>
      </table>
      <div class="col-md-2 col-lg-2">
        <a class="w-100 btn btn-primary" type="button" href="{% url 'job-task-add' job_id=job.id %}" title=""><i class="bi bi-plus"></i> Add Task</a> 
      </div>
    </div> 
  </div>
</div>
<script src="/static/js/lazy-listener.js"></script>
<script>
  let listenerMap = new Map([
    ["id_download_config", {
      "function": "event.appendChild(createSpinner('id_download_config'))",
      "type": "click"
    }]
  ])

  let deleteButtonList = document.getElementsByClassName("task-delete");
  for (var i = 0; i < deleteButtonList.length; i++) {
    listenerMap.set(deleteButtonList[i].id, {
      "function": "deleteModelObject(this.dataset['deleteUrl'], this.dataset['deleteElementId']);",
      "type": "click"
    })
  } 
  
  listenerMap.forEach(addListener)
</script>
{% endblock %}